### ISSUE TITLE
Could not find a declaration file for module 'duckdb-async'

### ISSUE THREAD

**Issue by vimota** [motherduckdb/duckdb-async#1]
Hey! 

This library looks awesome and is exactly what I need - thank you!! 🙏 I'm probably doing something wrong but after doing `yarn add duckdb-async`, and adding `import { Database } from "duckdb-async";` to my code, I run `yarn run tsc` and Typescript fails with:

```
yarn run v1.22.18
$ /Users/vimota/code/pinch/hellonode-builtin/node_modules/.bin/tsc
src/server.ts:3:26 - error TS7016: Could not find a declaration file for module 'duckdb-async'. '/Users/vimota/code/pinch/hellonode-builtin/node_modules/duckdb-async/dist/duckdb-async.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/duckdb-async` if it exists or add a new declaration (.d.ts) file containing `declare module 'duckdb-async';`

3 import { Database } from "duckdb-async";
```

I'm not totally sure if this is an issue with how the package is setup or whether I'm using yarn incorrectly 😅 If you have any idea, it'd be super appreciated!

**Comment by vimota** [comment]
Resolved 🤦  I had to set `"noImplicitAny"` to false!

**Comment by antonycourtney** [comment]
Hi @vimota I'm glad you found this library helpful, and that you got your issue resolved.
That said, I'm a little surprised you had to set `"noImplicitAny"` to resolve the issue; that shouldn't be necessary.
Just to demonstrate how this library can be used, I've pushed a tiny example repo here: [duckdb-async-example](https://github.com/motherduckdb/duckdb-async-example).
If you take a look at the [`tsconfig.json` ](https://github.com/motherduckdb/duckdb-async-example/blob/main/tsconfig.json) in that repo, you'll see that it doesn't specify `noImplicitAny`.
Hope that's helpful!
