### ISSUE TITLE
Bump duckdb to 0.7.0

### ISSUE THREAD

**Issue by archiewood** [motherduckdb/duckdb-async#2]
With most recent release would be great to get an update to duckdb-async!

**Comment by antonycourtney** [comment]
@archiewood Working on it!  It's straightforward to do the version bump but there are a couple of new methods in the underlying Node.JS API that I want to incorporate (and add tests for).  I'm at an in-person off-site all week but doing my best to squeeze in time for this. Rest assured will get this updated ASAP.

**Comment by archiewood** [comment]
There's probably some logic to upstreaming this to duckdb if they are open to it!

**Comment by antonycourtney** [comment]
@archiewood I've just published 0.7.0 of duckdb-async to npm. Please let me know if you encounter any issues.

To your earlier point: Yes, totally agree this should be upstreamed to duckdb. The DuckDb team are open to this. There's no real blocker to it happening, just a matter of carving out a few hours to deal with the build setup and CI.
