### ISSUE TITLE
Close() method missing in Connection class

### ISSUE THREAD

**Issue by brandantck** [motherduckdb/duckdb-async#22]
Hi, in the original duckdb docs there is a `close()` method in the Connection class, but seems like its missing in this library.

https://duckdb.org/docs/api/nodejs/reference#module_duckdb..Connection+close

**Comment by catapop84** [comment]
you can use `connection.conn.close();` , but this is just a dirty hack. Normally Connection should have an async close method.

**Comment by brandantck** [comment]
> you can use connection.conn.close(); , but this is just a dirty hack. Normally Connection should have an async close method.

Okay thanks, will probably do this for now.

**Comment by guicurcio** [comment]
bump, can I work on this? Any reason why the `close` wasn't in the `Connection` Classs?

**Comment by antonycourtney** [comment]
Sorry for the delayed response on this. I've added a `close` method to `Connection` in a commit to the `duckdb-latest` branch.  As soon as DuckDb publishes 0.10.0 to npm, I'll publish a 0.10.0 release of `duckdb-async` that will include this change. Thanks for reporting and for your patience.

**Comment by guicurcio** [comment]
Wow @antonycourtney awesome! Thanks a lot for your work!!
