### ISSUE TITLE
v8.0.0

### ISSUE THREAD

**Issue by archiewood** [motherduckdb/duckdb-async#7]
Had a go at bumping as per the previous upgrade to 0.7.1 but ran into an error

```
    src/duckdb-async.ts:216:5 - error TS2739: Type 'Promise<IpcResultStreamIterator>' is missing the following properties from type 'IpcResultStreamIterator': next, toArray, [Symbol.asyncIterator]
```

I guess the API has changed slightly, and I'm not really enough of a JS/TS person to figure out how!

**Comment by archiewood** [comment]
Context: We'd love to bump evidence to use the latest version of async
https://github.com/evidence-dev/evidence/issues/885

**Comment by antonycourtney** [comment]
Thanks for the reminder, @archiewood!  It's in my queue and will get to it ASAP.

**Comment by antonycourtney** [comment]
Upgraded to 0.8.0 and published to npm. Closing for now, please let me know if you encounter any issues.
