### ISSUE TITLE
NOT AN ISSUE - Thanks for making this package!

### ISSUE THREAD

**Issue by kuatroka** [motherduckdb/duckdb-async#8]
It works so much better than the main `duckdb` for nodejs. Please keep maintaining it and bumping up to new versions. And to be honest just because of the ease of use this should be the main package.

**Comment by RandomFractals** [comment]
yeah, `duckdb` node.js should be provide this out of the box and update their docs. Nobody uses callbacks in 2023 anymore 😄 

https://github.com/duckdb/duckdb/tree/master/tools/nodejs

Anyhoo, @antonycourtney thank you for creating this public DuckDB NodeJS lib wrapper!
